all : 
	ghc --make -outputdir obj -o bin/afcalc -i./src src/Main.hs

simple :
	ghc --make -outputdir obj -o bin/afcalc-simple -i./src src/Simple.hs

testtheta :
	ghc --make -outputdir obj -o bin/test-theta -i./src src/TestTheta.hs

